  GNU nano 4.8                                                                       /home/it-dev/.streamlit/secrets.toml                                                                                  
[mysql]
dialect = "mysql"
host = "192.213.213.200"
port = 3306
database = "sales_mart"
username = "root"
password = "Roy@l4b@d!"
